### ISSUE TITLE
Front-end development for the test instance

### ISSUE THREAD

**Issue by biancas20** [petabencana/riskmap#164]
08.08.23

- Ruthvik has given a demo to the peta team
- Nashin  suggested a few changes on CSS
- Ruthvik to give it out for an initial round of test without the CSS changes

**Comment by biancas20** [comment]
25.07.23

- Nashin has shared a presentation on the design of the testing instance - https://docs.google.com/presentation/d/1hAIVcEZ7qnChhIhZuzdll0eN9g5QAdqggllUYhT8rZA/edit#slide=id.g1e51d9c5f2a_0_0

**Comment by biancas20** [comment]
01.08.23

- Ruthvik has started working on the front-end

**Comment by biancas20** [comment]
14.08.23

- Back-end is good to go
- Small changes on button, and one translation change
- Will be ready for demo on Wednesday (16th August)
- One more round of testing for CSS (button, design) changes, which can be done post Wednesday

**Comment by ruthvik129** [comment]
Development going on [here](https://github.com/petabencana/cognicity-cards-ng/pull/48)
