### ISSUE TITLE
#flood: Missing icon in summary card and small glitch in the report detail

### ISSUE THREAD

**Issue by anaritawidya** [petabencana/riskmap#45]
When we don't upload a picture, the pic should be the flood icon in the summary card and in the report detail as well
![image](https://user-images.githubusercontent.com/34257163/88882968-433bb780-d25d-11ea-83c1-3295012903c7.png)

should be the same as the current icon in the report detail, but remove the small corrupt image in the corner

![image](https://user-images.githubusercontent.com/34257163/88883470-a2e69280-d25e-11ea-985f-53452d7c6595.png)

**Comment by silvergravel** [comment]
fixed. awaiting new flood icon from @anaritawidya . then will replace the old (drop one) with the new one. keeping this open for now.

**Comment by anaritawidya** [comment]
@Deepthi-Chand the icon on summary card and report detail should be the same, currently the icon on summary card is the flood icon with water drop.
![image](https://user-images.githubusercontent.com/34257163/92434668-a14bab00-f1ca-11ea-86ef-db239baba6fa.png)
