### ISSUE TITLE
#earthquake: twitter bot sometimes reply incorrectly

### ISSUE THREAD

**Issue by anaritawidya** [petabencana/riskmap#51]
Still find an issue with the twitter bot for gempa, the same issue as I reported to you weeks ago. It replies with the right thing when people tweet/retweet "gempa", but when the keyword have variations like "Gempa" "gempa." or "gempaaa", the bot still reply with banjir. https://twitter.com/infoBMKG/status/1280362885164630021?s=19

**Comment by Deepthi-Chand** [comment]
@anaritawidya can you verify if this works now with latest deployment

**Comment by anaritawidya** [comment]
> @anaritawidya can you verify if this works now with latest deployment

Ok, will monitor it on twitter. so far it works fine, will let you know if there's an issue with the bot
